name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy via SFTP
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 🚀 Create target directory if not exists
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        port: 22
        script: |
          mkdir -p /home/git/site-html/wi-ticket-site/

    - name: 📂 Deploy files via SFTP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        port: 22  # Porta padrão do SFTP
        source: "."  # Arquivos locais a serem enviados
        target: "/home/git/site-html/wi-ticket-site/"  # Diretório de destino no servidor

    - name: 📂 Deploy files via www
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        port: 22  # Porta padrão do SFTP
        source: "."  # Arquivos locais a serem enviados
        target: "/var/www/html/wi-ticket-site/"  # Diretório de destino no servidor
